name: integracion continua con react.js

on: 
  pull_request:
    branches: [ master ]

jobs: 
  ci_to_master:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/ckeckout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build